# Site settings
title: No mitä sä sitten voit syödä?
email: darth.kipsu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruokapäiväkirjaa ylläpitää lähes vegaani kasvissyöjäpariskunta Helsingin vihreästä kuplasta.
  Blogin tarkoituksena on avata vegaanin elämää rennolla otteella kulinaristisessa mielessä.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mitasasyot.fi" # the base hostname & protocol for your site
github_username:  nmssvs

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/sivu:num/"
